name: Deploy Init Scripts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move init.sh files
        run: |
          mkdir -p ./dist

          # move root init.sh file
          mv ./init.sh ./dist/init.sh

          # move language init.sh files
          for lang_path in t/*; do
              lang=$(basename "$lang_path")
              mkdir -p "./dist/$lang"
              mv "$lang_path/init.sh" "./dist/$lang/init.sh"
          done

      - name: Upload dist directory for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: github-pages

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
